#!/usr/bin/env python3
"""
add_gee_layers.py — the layer registry for the flood-dataset pipeline.

This file is the SINGLE SOURCE OF TRUTH for which GEE layers the pipeline
exports. Every script reads the registry from here:

  - Script 2 (submit) exports one GeoTIFF per ENABLED layer.
  - Script 4 (metadata) reports, per activation, which enabled layers arrived.

To add your own layer, copy one of the TEMPLATE blocks at the bottom, give it a
unique `key` and `filename`, set the GEE `collection`, `bands`, `resolution_m`
and (for a time series) `n_days`, and append the resulting LayerSpec to
`CUSTOM_LAYERS`. Toggle layers on/off in config.py — you do not edit this file
to disable a layer.

Three layer KINDS:

  "static"    one image, no time dimension (MERIT, Soil, ESA_PW). Band count is
              fixed. Provide a `builder(region) -> ee.Image`.

  "temporal"  one band per antecedent day (Precipitation, SoilMoisture). Band
              count = n_days (set per layer / overridable in config.py). Provide
              a `builder(region, event_date, n_days) -> ee.Image`. Exported over
              the AOI expanded by a buffer at the layer's native resolution.

  "composite" a pre-event median composite with adaptive coverage logic (S1, S2
              indices). These have bespoke builders that live in Script 2 and are
              referenced here by `builder_name`; `builder` is left None.

A LayerSpec is the only object the rest of the pipeline needs to know about.
"""

from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Callable, List, Optional

# ee is imported lazily by the builders so that this module can be imported
# (e.g. by config.py / Script 4) without an Earth Engine session.


# ─── LAYER SPEC ───────────────────────────────────────────────────────────────

@dataclass
class LayerSpec:
    key: str                              # registry key, e.g. "Precipitation"
    filename: str                         # output GeoTIFF, e.g. "Precipitation.tif"
    kind: str                             # "static" | "temporal" | "composite"
    bands: Optional[int] = None           # fixed band count (static/composite)
    resolution_m: float = 10.0            # nominal native resolution, metres
    n_days: Optional[int] = None          # temporal layers only (band count)
    buffered: bool = False                # export over buffered AOI (temporal)
    builder: Optional[Callable] = None    # static/temporal builders live here
    builder_name: Optional[str] = None    # composite builders live in Script 2
    description: str = ""

    def band_count(self) -> int:
        """Expected number of bands for this layer given its current config."""
        if self.kind == "temporal":
            return int(self.n_days)
        return int(self.bands)


# ─── STATIC BUILDERS ──────────────────────────────────────────────────────────

def build_merit(region):
    """MERIT Hydro 4-band: Elevation, FlowDirection, UDA, HAND."""
    import ee
    merit = ee.Image("MERIT/Hydro/v1_0_1")
    return (
        merit.select(["elv", "dir", "upa", "hnd"])
             .toFloat()
             .rename(["Elevation", "FlowDirection", "UDA", "HAND"])
             .unmask(-9999)
    )


def build_soil(region):
    """SoilGrids topsoil (0 cm) clay + sand percentage."""
    import ee
    clay = (ee.Image("OpenLandMap/SOL/SOL_CLAY-WFRACTION_USDA-3A1A1A_M/v02")
            .select("b0").rename("Clay"))
    sand = (ee.Image("OpenLandMap/SOL/SOL_SAND-WFRACTION_USDA-3A1A1A_M/v02")
            .select("b0").rename("Sand"))
    return ee.Image.cat([clay, sand]).unmask(-9999)


def build_esa_pw(region):
    """ESA WorldCover 2021 permanent water (class 80) binary mask."""
    import ee
    esa = ee.ImageCollection("ESA/WorldCover/v200").first()
    return esa.eq(80).rename("PermanentWater").toUint8().unmask(0)


# ─── TEMPORAL BUILDERS ────────────────────────────────────────────────────────

def build_precipitation(region, event_date: date, n_days: int):
    """
    GPM-IMERG V07 daily total precipitation for the n_days antecedent days,
    event day excluded: bands [event_date-n_days ... event_date-1], oldest first.
    IMERG gives a half-hourly rate (mm/hr); the daily total (mm) sums the day's
    rates x 0.5 hr. Bands named 'Precipitation_YYYYMMDD'.
    """
    import ee
    bands = []
    for offset in range(n_days, 0, -1):
        d     = event_date - timedelta(days=offset)
        dstr  = d.strftime("%Y%m%d")
        start = d.isoformat()
        end   = (d + timedelta(days=1)).isoformat()
        col   = (ee.ImageCollection("NASA/GPM_L3/IMERG_V07")
                 .filterDate(start, end).select("precipitation"))
        daily = col.sum().multiply(0.5)
        img = ee.Image(ee.Algorithms.If(
            col.size().gt(0),
            daily.rename(f"Precipitation_{dstr}"),
            ee.Image.constant(9999).rename(f"Precipitation_{dstr}").toFloat()
        )).unmask(9999)
        bands.append(img)
    return ee.Image(bands)


def build_soil_moisture(region, event_date: date, n_days: int):
    """
    SMAP L4 surface soil moisture (NASA/SMAP/SPL4SMGP/008) for the n_days
    antecedent days, event day excluded. Bands named 'SM_YYYYMMDD'.
    """
    import ee
    bands = []
    for offset in range(n_days, 0, -1):
        d     = event_date - timedelta(days=offset)
        dstr  = d.strftime("%Y%m%d")
        start = d.isoformat()
        end   = (d + timedelta(days=1)).isoformat()
        col = (ee.ImageCollection("NASA/SMAP/SPL4SMGP/008")
               .filterDate(start, end).select("sm_surface"))
        img = ee.Image(ee.Algorithms.If(
            col.size().gt(0),
            col.first().rename(f"SM_{dstr}"),
            ee.Image.constant(9999).rename(f"SM_{dstr}").toFloat()
        )).unmask(9999)
        bands.append(img)
    return ee.Image(bands)


# ─── CORE LAYERS (the seven shipped with the dataset) ─────────────────────────
# S1 and S2 indices are "composite" layers: their adaptive-window / cloud
# builders live in Script 2 and are referenced here by builder_name.

CORE_LAYERS: List[LayerSpec] = [
    LayerSpec(
        key="S1", filename="S1_VV_VH.tif", kind="composite",
        bands=2, resolution_m=10.0, builder_name="build_s1",
        description="Sentinel-1 SAR pre-event median composite (VV, VH dB).",
    ),
    LayerSpec(
        key="S2_indices", filename="S2_NDVI_NDBI.tif", kind="composite",
        bands=2, resolution_m=10.0, builder_name="build_s2_indices",
        description="Sentinel-2 pre-event NDVI + NDBI composite.",
    ),
    LayerSpec(
        key="MERIT", filename="MERIT.tif", kind="static",
        bands=4, resolution_m=90.0, builder=build_merit,
        description="MERIT Hydro: elevation, flow direction, UDA, HAND.",
    ),
    LayerSpec(
        key="Soil", filename="Soil.tif", kind="static",
        bands=2, resolution_m=250.0, builder=build_soil,
        description="SoilGrids topsoil clay % + sand % (0-5 cm).",
    ),
    LayerSpec(
        key="ESA_PW", filename="ESA_WorldCover_PermanentWater.tif", kind="static",
        bands=1, resolution_m=10.0, builder=build_esa_pw,
        description="ESA WorldCover 2021 class-80 permanent-water mask "
                    "(the released permanent-water layer).",
    ),
    LayerSpec(
        key="Precipitation", filename="Precipitation.tif", kind="temporal",
        n_days=30, resolution_m=11000.0, buffered=True,
        builder=build_precipitation,
        description="GPM-IMERG V07 daily precipitation (mm/day).",
    ),
    LayerSpec(
        key="SoilMoisture", filename="SoilMoisture.tif", kind="temporal",
        n_days=30, resolution_m=9500.0, buffered=True,
        builder=build_soil_moisture,
        description="SMAP L4 daily surface soil moisture (m3/m3).",
    ),
]


# ─── CUSTOM LAYERS ────────────────────────────────────────────────────────────
# Add your own layers here. Copy a TEMPLATE below, edit it, append it.

CUSTOM_LAYERS: List[LayerSpec] = [
    # e.g. STATIC_TEMPLATE, MY_TEMPORAL_LAYER, ...
]


# ─── TEMPLATES (copy, edit, append to CUSTOM_LAYERS) ──────────────────────────
#
# STATIC layer — one image, fixed bands. Define a builder(region) -> ee.Image
# and a LayerSpec that points at it:
#
#   def build_my_static(region):
#       import ee
#       return ee.Image("YOUR/COLLECTION").select(["b1"]).rename(["MyBand"]).unmask(-9999)
#
#   STATIC_TEMPLATE = LayerSpec(
#       key="MyStatic", filename="MyStatic.tif", kind="static",
#       bands=1, resolution_m=100.0, builder=build_my_static,
#       description="What this layer is.",
#   )
#
# TEMPORAL layer — one band per antecedent day. Define a
# builder(region, event_date, n_days) -> ee.Image that returns an n_days-band
# image (see build_precipitation for the pattern), then:
#
#   TEMPORAL_TEMPLATE = LayerSpec(
#       key="MyDaily", filename="MyDaily.tif", kind="temporal",
#       n_days=10, resolution_m=9000.0, buffered=True, builder=build_my_daily,
#       description="Daily series of something.",
#   )


# ─── ACCESS ───────────────────────────────────────────────────────────────────

def all_layers() -> List[LayerSpec]:
    """Every registered layer (core + custom), regardless of enabled state."""
    return CORE_LAYERS + CUSTOM_LAYERS


def core_keys() -> List[str]:
    """Keys of the core layers. An event missing one of these is incomplete and
    is excluded from the catalog; missing a custom layer only is tolerated."""
    return [spec.key for spec in CORE_LAYERS]


def layer_by_key(key: str) -> Optional[LayerSpec]:
    for spec in all_layers():
        if spec.key == key:
            return spec
    return None
